# Generated by Django 4.1.1 on 2022-09-30 15:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exercicio', '0001_initial'),
        ('usuario', '0001_initial'),
        ('momento_treino', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Treino',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dt_criacao', models.DateTimeField(auto_now_add=True)),
                ('dt_update', models.DateTimeField(auto_now=True)),
                ('titulo', models.CharField(max_length=30)),
                ('cpf_autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.usuario')),
                ('exercicios', models.ManyToManyField(to='exercicio.exercicio')),
                ('id_momento_treino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='momento_treino.momentotreino')),
            ],
            options={
                'db_table': 'treino',
            },
        ),
    ]
