# Generated by Django 4.1.1 on 2022-09-28 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0001_initial'),
        ('core', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dieta',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.basemodel')),
                ('titulo', models.CharField(max_length=30)),
                ('max_calorias_diarias', models.IntegerField()),
                ('min_calorias_diarias', models.IntegerField()),
                ('tipo', models.CharField(blank=True, max_length=15)),
                ('cpf_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.usuario')),
            ],
            options={
                'db_table': 'dieta',
            },
            bases=('core.basemodel',),
        ),
    ]
