# Generated by Django 4.1.1 on 2022-09-30 15:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dieta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dt_criacao', models.DateTimeField(auto_now_add=True)),
                ('dt_update', models.DateTimeField(auto_now=True)),
                ('titulo', models.CharField(max_length=30)),
                ('max_calorias_diarias', models.IntegerField()),
                ('min_calorias_diarias', models.IntegerField()),
                ('tipo', models.CharField(blank=True, max_length=15)),
                ('cpf_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.usuario')),
            ],
            options={
                'db_table': 'dieta',
            },
        ),
    ]
