# Generated by Django 4.1.1 on 2022-09-28 15:05

from django.db import migrations, models
import django.db.models.deletion
import enumchoicefield.fields
import momento_treino.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0001_initial'),
        ('core', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='MomentoTreino',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.basemodel')),
                ('dia_semana', enumchoicefield.fields.EnumChoiceField(enum_class=momento_treino.models.DiaSemanaEnum, max_length=7)),
                ('horario_inicio', models.TimeField()),
                ('horario_fim', models.TimeField()),
                ('cpf_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.usuario')),
            ],
            options={
                'db_table': 'momento_treino',
            },
            bases=('core.basemodel',),
        ),
    ]
