# Generated by Django 4.1.1 on 2022-09-30 15:31

from django.db import migrations, models
import django.db.models.deletion
import enumchoicefield.fields
import momento_treino.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MomentoTreino',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dt_criacao', models.DateTimeField(auto_now_add=True)),
                ('dt_update', models.DateTimeField(auto_now=True)),
                ('dia_semana', enumchoicefield.fields.EnumChoiceField(enum_class=momento_treino.models.DiaSemanaEnum, max_length=7)),
                ('horario_inicio', models.TimeField()),
                ('horario_fim', models.TimeField()),
                ('cpf_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.usuario')),
            ],
            options={
                'db_table': 'momento_treino',
            },
        ),
    ]
