# Generated by Django 4.1.1 on 2022-09-30 15:31

import django.core.validators
from django.db import migrations, models
import enumchoicefield.fields
import usuario.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('cpf', models.CharField(max_length=11, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(11)])),
                ('is_admin', models.BooleanField(default=False)),
                ('nome_completo', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=247, unique=True)),
                ('senha', models.CharField(max_length=247)),
                ('peso', models.DecimalField(blank=True, decimal_places=2, max_digits=5)),
                ('altura', models.IntegerField(blank=True)),
                ('dt_nascimento', models.DateField()),
                ('objetivo', enumchoicefield.fields.EnumChoiceField(enum_class=usuario.models.ObjetivosEnum, max_length=6)),
                ('dt_criacao', models.DateTimeField(auto_now_add=True)),
                ('dt_update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
    ]
