# Generated by Django 4.1.1 on 2022-09-28 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='meta',
            table='meta',
        ),
    ]
