# Generated by Django 4.1.1 on 2022-09-28 14:07

from django.db import migrations, models
import django.db.models.deletion
import enumchoicefield.fields
import exercicio.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercicio',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.basemodel')),
                ('nome', models.CharField(max_length=30)),
                ('detalhe', models.TextField(max_length=500)),
                ('repeticoes', models.IntegerField()),
                ('temp_descanso', models.IntegerField()),
                ('nivel_dificuldade', enumchoicefield.fields.EnumChoiceField(enum_class=exercicio.models.NivelDificuldadeEnum, max_length=7)),
            ],
            options={
                'db_table': 'exercicio',
            },
            bases=('core.basemodel',),
        ),
    ]
