# Generated by Django 4.1.1 on 2022-09-28 11:20

from django.db import migrations, models
import enumchoicefield.fields
import exercicio.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercicio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=30)),
                ('detalhe', models.TextField(max_length=500)),
                ('repeticoes', models.IntegerField()),
                ('temp_descanso', models.IntegerField()),
                ('nivel_dificuldade', enumchoicefield.fields.EnumChoiceField(enum_class=exercicio.models.NivelDificuldadeEnum, max_length=7)),
                ('dt_criacao', models.DateTimeField(auto_now_add=True)),
                ('dt_update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'exercicio',
            },
        ),
    ]
